// Official FIFA World Cup 2026 Match Schedule
// Source: FWC26_Match_Schedule_v17_10042026_EN.pdf
// All times are Eastern Time (ET)

// Group stage results (M1-M72). Numbered chronologically per FIFA convention.
// Venue/time intentionally omitted for these — historical matchup+date+result only.
export const GROUP_SCHEDULE = [
  // Matchday 1
  { num: 1,  date: 'Thu Jun 11', home: 'Mexico',        away: 'South Africa',  result: '2-0', venue: 'Mexico City' },
  { num: 2,  date: 'Thu Jun 11', home: 'Korea Republic', away: 'Czechia',      result: '2-1', venue: 'Guadalajara' },
  { num: 3,  date: 'Fri Jun 12', home: 'Canada',         away: 'Bosnia and Herzegovina', result: '1-1', venue: 'Toronto' },
  { num: 4,  date: 'Fri Jun 12', home: 'United States',  away: 'Paraguay',     result: '4-1', venue: 'Los Angeles' },
  { num: 5,  date: 'Sat Jun 13', home: 'Qatar',          away: 'Switzerland',  result: '1-1', venue: 'San Francisco Bay Area' },
  { num: 6,  date: 'Sat Jun 13', home: 'Brazil',         away: 'Morocco',      result: '1-1', venue: 'New York/New Jersey' },
  { num: 7,  date: 'Sat Jun 13', home: 'Haiti',          away: 'Scotland',     result: '0-1', venue: 'Boston' },
  { num: 8,  date: 'Sun Jun 14', home: 'Australia',      away: 'Türkiye',      result: '2-0', venue: 'Vancouver' },
  { num: 9,  date: 'Sun Jun 14', home: 'Germany',        away: 'Curaçao',      result: '7-1', venue: 'Houston' },
  { num: 10, date: 'Sun Jun 14', home: 'Ivory Coast',    away: 'Ecuador',      result: '1-0', venue: 'Philadelphia' },
  { num: 11, date: 'Sun Jun 14', home: 'Netherlands',    away: 'Japan',        result: '2-2', venue: 'Dallas' },
  { num: 12, date: 'Sun Jun 14', home: 'Sweden',         away: 'Tunisia',      result: '5-1', venue: 'Monterrey' },
  { num: 13, date: 'Mon Jun 15', home: 'Belgium',        away: 'Egypt',        result: '1-1', venue: 'Seattle' },
  { num: 14, date: 'Mon Jun 15', home: 'Iran',           away: 'New Zealand',  result: '2-2', venue: 'Los Angeles' },
  { num: 15, date: 'Mon Jun 15', home: 'Spain',          away: 'Cape Verde',   result: '0-0', venue: 'Atlanta' },
  { num: 16, date: 'Mon Jun 15', home: 'Saudi Arabia',   away: 'Uruguay',      result: '1-1', venue: 'Miami' },
  { num: 17, date: 'Tue Jun 16', home: 'France',         away: 'Senegal',      result: '3-1', venue: 'New York/New Jersey' },
  { num: 18, date: 'Tue Jun 16', home: 'Iraq',           away: 'Norway',       result: '1-4', venue: 'Boston' },
  { num: 19, date: 'Tue Jun 16', home: 'Argentina',      away: 'Algeria',      result: '3-0', venue: 'Kansas City' },
  { num: 20, date: 'Wed Jun 17', home: 'Austria',        away: 'Jordan',       result: '3-1', venue: 'San Francisco Bay Area' },
  { num: 21, date: 'Wed Jun 17', home: 'Portugal',       away: 'DR Congo',     result: '1-1', venue: 'Houston' },
  { num: 22, date: 'Wed Jun 17', home: 'Uzbekistan',     away: 'Colombia',     result: '1-3', venue: 'Mexico City' },
  { num: 23, date: 'Wed Jun 17', home: 'England',        away: 'Croatia',      result: '4-2', venue: 'Dallas' },
  { num: 24, date: 'Wed Jun 17', home: 'Ghana',          away: 'Panama',       result: '1-0', venue: 'Toronto' },
  // Matchday 2
  { num: 25, date: 'Thu Jun 18', home: 'Czechia',        away: 'South Africa', result: '1-1', venue: 'Atlanta' },
  { num: 26, date: 'Thu Jun 18', home: 'Mexico',         away: 'Korea Republic', result: '1-0', venue: 'Guadalajara' },
  { num: 27, date: 'Thu Jun 18', home: 'Switzerland',    away: 'Bosnia and Herzegovina', result: '4-1', venue: 'Los Angeles' },
  { num: 28, date: 'Thu Jun 18', home: 'Canada',         away: 'Qatar',        result: '6-0', venue: 'Vancouver' },
  { num: 29, date: 'Fri Jun 19', home: 'Scotland',       away: 'Morocco',      result: '0-1', venue: 'Boston' },
  { num: 30, date: 'Fri Jun 19', home: 'Brazil',         away: 'Haiti',        result: '3-0', venue: 'Philadelphia' },
  { num: 31, date: 'Fri Jun 19', home: 'United States',  away: 'Australia',    result: '2-0', venue: 'Seattle' },
  { num: 32, date: 'Fri Jun 19', home: 'Türkiye',        away: 'Paraguay',     result: '0-1', venue: 'San Francisco Bay Area' },
  { num: 33, date: 'Sat Jun 20', home: 'Germany',        away: 'Ivory Coast',  result: '2-1', venue: 'Toronto' },
  { num: 34, date: 'Sat Jun 20', home: 'Ecuador',        away: 'Curaçao',      result: '0-0', venue: 'Kansas City' },
  { num: 35, date: 'Sat Jun 20', home: 'Netherlands',    away: 'Sweden',       result: '5-1', venue: 'Houston' },
  { num: 36, date: 'Sun Jun 21', home: 'Tunisia',        away: 'Japan',        result: '0-4', venue: 'Monterrey' },
  { num: 37, date: 'Sun Jun 21', home: 'Belgium',        away: 'Iran',         result: '0-0', venue: 'Los Angeles' },
  { num: 38, date: 'Sun Jun 21', home: 'New Zealand',    away: 'Egypt',        result: '1-3', venue: 'Vancouver' },
  { num: 39, date: 'Sun Jun 21', home: 'Spain',          away: 'Saudi Arabia', result: '4-0', venue: 'Atlanta' },
  { num: 40, date: 'Sun Jun 21', home: 'Uruguay',        away: 'Cape Verde',   result: '2-2', venue: 'Miami' },
  { num: 41, date: 'Mon Jun 22', home: 'France',         away: 'Iraq',         result: '3-0', venue: 'Philadelphia' },
  { num: 42, date: 'Mon Jun 22', home: 'Norway',         away: 'Senegal',      result: '3-2', venue: 'New York/New Jersey' },
  { num: 43, date: 'Mon Jun 22', home: 'Argentina',      away: 'Austria',      result: '2-0', venue: 'Dallas' },
  { num: 44, date: 'Mon Jun 22', home: 'Jordan',         away: 'Algeria',      result: '1-2', venue: 'San Francisco Bay Area' },
  { num: 45, date: 'Tue Jun 23', home: 'Portugal',       away: 'Uzbekistan',   result: '5-0', venue: 'Houston' },
  { num: 46, date: 'Tue Jun 23', home: 'Colombia',       away: 'DR Congo',     result: '1-0', venue: 'Guadalajara' },
  { num: 47, date: 'Tue Jun 23', home: 'England',        away: 'Ghana',        result: '0-0', venue: 'Boston' },
  { num: 48, date: 'Tue Jun 23', home: 'Panama',         away: 'Croatia',      result: '0-1', venue: 'Toronto' },
  // Matchday 3
  { num: 49, date: 'Wed Jun 24', home: 'Czechia',        away: 'Mexico',       result: '0-3', venue: 'Mexico City' },
  { num: 50, date: 'Wed Jun 24', home: 'South Africa',   away: 'Korea Republic', result: '1-0', venue: 'Monterrey' },
  { num: 51, date: 'Wed Jun 24', home: 'Switzerland',    away: 'Canada',       result: '2-1', venue: 'Vancouver' },
  { num: 52, date: 'Wed Jun 24', home: 'Bosnia and Herzegovina', away: 'Qatar', result: '3-1', venue: 'Seattle' },
  { num: 53, date: 'Wed Jun 24', home: 'Scotland',       away: 'Brazil',       result: '0-3', venue: 'Miami' },
  { num: 54, date: 'Wed Jun 24', home: 'Morocco',        away: 'Haiti',        result: '4-2', venue: 'Atlanta' },
  { num: 55, date: 'Thu Jun 25', home: 'Türkiye',        away: 'United States', result: '3-2', venue: 'Los Angeles' },
  { num: 56, date: 'Thu Jun 25', home: 'Paraguay',       away: 'Australia',    result: '0-0', venue: 'San Francisco Bay Area' },
  { num: 57, date: 'Thu Jun 25', home: 'Curaçao',        away: 'Ivory Coast',  result: '0-2', venue: 'Philadelphia' },
  { num: 58, date: 'Thu Jun 25', home: 'Ecuador',        away: 'Germany',      result: '2-1', venue: 'New York/New Jersey' },
  { num: 59, date: 'Thu Jun 25', home: 'Japan',          away: 'Sweden',       result: '1-1', venue: 'Dallas' },
  { num: 60, date: 'Thu Jun 25', home: 'Tunisia',        away: 'Netherlands',  result: '1-3', venue: 'Kansas City' },
  { num: 61, date: 'Fri Jun 26', home: 'Egypt',          away: 'Iran',         result: '1-1', venue: 'Seattle' },
  { num: 62, date: 'Fri Jun 26', home: 'New Zealand',    away: 'Belgium',      result: '1-5', venue: 'Vancouver' },
  { num: 63, date: 'Fri Jun 26', home: 'Cape Verde',     away: 'Saudi Arabia', result: '0-0', venue: 'Houston' },
  { num: 64, date: 'Fri Jun 26', home: 'Uruguay',        away: 'Spain',        result: '0-1', venue: 'Guadalajara' },
  { num: 65, date: 'Fri Jun 26', home: 'Norway',         away: 'France',       result: '1-4', venue: 'Boston' },
  { num: 66, date: 'Fri Jun 26', home: 'Senegal',        away: 'Iraq',         result: '5-0', venue: 'Toronto' },
  { num: 67, date: 'Sat Jun 27', home: 'Algeria',        away: 'Austria',      result: '3-3', venue: 'Kansas City' },
  { num: 68, date: 'Sat Jun 27', home: 'Jordan',         away: 'Argentina',    result: '1-3', venue: 'Dallas' },
  { num: 69, date: 'Sat Jun 27', home: 'Colombia',       away: 'Portugal',     result: '0-0', venue: 'Miami' },
  { num: 70, date: 'Sat Jun 27', home: 'DR Congo',       away: 'Uzbekistan',   result: '3-1', venue: 'Atlanta' },
  { num: 71, date: 'Sat Jun 27', home: 'Panama',         away: 'England',      result: '0-2', venue: 'New York/New Jersey' },
  { num: 72, date: 'Sat Jun 27', home: 'Croatia',        away: 'Ghana',        result: '2-1', venue: 'Philadelphia' },
];

// Abbreviations for venues too long to fit in a 130px bracket slot
export const VENUE_SHORT = {
  'San Francisco Bay Area': 'Bay Area',
  'New York/New Jersey':    'NY/NJ',
  'Monterrey':              'MTY',
  'Los Angeles':            'LA',
  'Kansas City':            'KC',
  'Mexico City':            'MEX',
};

export const MATCH_SCHEDULE = {
  // Round of 32
  73:  { date: 'Sun Jun 28', time: '15:00 ET', venue: 'Los Angeles'           },
  74:  { date: 'Mon Jun 29', time: '16:30 ET', venue: 'Boston'                },
  75:  { date: 'Mon Jun 29', time: '21:00 ET', venue: 'Monterrey'             },
  76:  { date: 'Mon Jun 29', time: '13:00 ET', venue: 'Houston'               },
  77:  { date: 'Tue Jun 30', time: '17:00 ET', venue: 'New York/New Jersey'   },
  78:  { date: 'Tue Jun 30', time: '13:00 ET', venue: 'Dallas'                },
  79:  { date: 'Tue Jun 30', time: '21:00 ET', venue: 'Mexico City'           },
  80:  { date: 'Wed Jul 1',  time: '12:00 ET', venue: 'Atlanta'               },
  81:  { date: 'Wed Jul 1',  time: '20:00 ET', venue: 'San Francisco Bay Area'},
  82:  { date: 'Wed Jul 1',  time: '16:00 ET', venue: 'Seattle'               },
  83:  { date: 'Thu Jul 2',  time: '19:00 ET', venue: 'Toronto'               },
  84:  { date: 'Thu Jul 2',  time: '15:00 ET', venue: 'Los Angeles'           },
  85:  { date: 'Thu Jul 2',  time: '23:00 ET', venue: 'Vancouver'             },
  86:  { date: 'Fri Jul 3',  time: '18:00 ET', venue: 'Miami'                 },
  87:  { date: 'Fri Jul 3',  time: '21:30 ET', venue: 'Kansas City'           },
  88:  { date: 'Fri Jul 3',  time: '14:00 ET', venue: 'Dallas'                },
  // Round of 16
  89:  { date: 'Sat Jul 4',  time: '17:00 ET', venue: 'Philadelphia'          },
  90:  { date: 'Sat Jul 4',  time: '13:00 ET', venue: 'Houston'               },
  91:  { date: 'Sun Jul 5',  time: '16:00 ET', venue: 'New York/New Jersey'   },
  92:  { date: 'Sun Jul 5',  time: '20:00 ET', venue: 'Mexico City'           },
  93:  { date: 'Mon Jul 6',  time: '15:00 ET', venue: 'Dallas'                },
  94:  { date: 'Mon Jul 6',  time: '20:00 ET', venue: 'Seattle'               },
  95:  { date: 'Tue Jul 7',  time: '12:00 ET', venue: 'Atlanta'               },
  96:  { date: 'Tue Jul 7',  time: '16:00 ET', venue: 'Vancouver'             },
  // Quarterfinals
  97:  { date: 'Thu Jul 9',  time: '16:00 ET', venue: 'Boston'                },
  98:  { date: 'Fri Jul 10', time: '15:00 ET', venue: 'Los Angeles'           },
  99:  { date: 'Sat Jul 11', time: '17:00 ET', venue: 'Miami'                 },
  100: { date: 'Sat Jul 11', time: '21:00 ET', venue: 'Kansas City'           },
  // Semifinals
  101: { date: 'Tue Jul 14', time: '15:00 ET', venue: 'Dallas'                },
  102: { date: 'Wed Jul 15', time: '15:00 ET', venue: 'Atlanta'               },
  // Bronze Final
  103: { date: 'Sat Jul 18', time: '17:00 ET', venue: 'Miami'                 },
  // Final
  104: { date: 'Sun Jul 19', time: '15:00 ET', venue: 'New York/New Jersey'   },
};
